-- archive-poc/sql/comments.pg.sql
--
-- Content-comments store (comments lane). Pulls content comments OUT of WordPress
-- so the comment modal stops booting WP (~1–3s) and reads from this table on the
-- archive-poc FPM pool (~50ms). Lives in the `discovery` schema alongside likes +
-- article_blobs + content_item (coord §3i — one postgres, per-strangler schema).
--
-- Scope = CONTENT comments only (loothprint, video, post-imgcap, post, shorty,
-- coe-questions, ajde_events). shop_order WooCommerce order-notes are EXCLUDED
-- (internal order data, not community comments). Forum replies stay in bb-mirror's
-- `forums` schema — out of scope.
--
-- Keyed to content exactly like discovery.likes: (post_type, item_id) where
-- item_id mirrors wp_posts.ID. Threading via self-referential parent_id. Author
-- identity is the shared user_uuid contract (resolved to a live profile card at
-- read time via /profile-api/v0/users); legacy anonymous commenters (no WP user)
-- carry a frozen author_name with a NULL user_uuid.
--
-- Reactions on comments are a FAST-FOLLOW (Ian, 2026-06-04): a future
-- comment_reactions(comment_id, user_uuid, kind, created_at) — mirror of
-- discovery.likes — drops in against this table's surrogate id. NOT built here.
--
-- Apply as the schema OWNER (archive-poc) so it owns the table (read side) and the
-- looth-dev write grants below attach. search_path assumed `discovery, public`:
--   sudo -u archive-poc psql -d looth -v ON_ERROR_STOP=1 \
--     -c 'SET search_path = discovery, public' -f sql/comments.pg.sql

CREATE TABLE IF NOT EXISTS comments (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_type     TEXT        NOT NULL,                 -- raw WP post_type of the content item
  item_id       BIGINT      NOT NULL,                 -- mirrors wp_posts.ID (= comment_post_ID)
  parent_id     BIGINT      REFERENCES comments(id) ON DELETE CASCADE,  -- threading (NULL = top level)
  user_uuid     UUID,                                 -- author (shared identity); NULL for legacy anon
  author_wp_id  BIGINT,                               -- author's WP user id at write time (traceability)
  author_name   TEXT,                                 -- frozen name for anon / display fallback
  body          TEXT        NOT NULL,
  status        TEXT        NOT NULL DEFAULT 'approved', -- approved | pending | spam | trash
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  -- Idempotent backfill key: the source wp_comments.comment_ID. NULL for net-new
  -- comments posted through the write endpoint. UNIQUE so re-running the backfill
  -- updates-in-place instead of duplicating the thread.
  legacy_wp_id  BIGINT UNIQUE
);

-- Thread fetch: all rows for one content item, oldest-first within the item.
CREATE INDEX IF NOT EXISTS idx_comments_item ON comments (post_type, item_id, created_at);
-- Child lookup when assembling threads / counting replies.
CREATE INDEX IF NOT EXISTS idx_comments_parent ON comments (parent_id);
-- "my comments" / author re-resolution surfaces.
CREATE INDEX IF NOT EXISTS idx_comments_user ON comments (user_uuid);

-- Write-side role: `looth-dev` runs the comment-post write endpoint (looth-dev FPM
-- pool — it boots WP to validate the login cookie) + the backfill
-- (sudo -u looth-dev). Same shared write-side role article_blobs uses (coord §3i).
-- The schema owner (archive-poc) keeps ownership → it reads the table for the modal
-- via its own pool/role.
GRANT USAGE  ON SCHEMA discovery TO "looth-dev";
GRANT SELECT, INSERT, UPDATE, DELETE ON comments TO "looth-dev";
GRANT USAGE, SELECT ON SEQUENCE comments_id_seq TO "looth-dev";

-- profile-app stays a read-only cross-schema consumer (future composite views),
-- matching the existing discovery grants. Harmless if it never reads this table.
GRANT SELECT ON comments TO "profile-app";

-- bb-mirror (the Hub feed) reads comment counts to badge content cards in the
-- unified feed + power the inline comment modal — same read-only cross-schema
-- consumer pattern it already uses for discovery.content_item.
GRANT SELECT ON comments TO "bb-mirror";
