#!/usr/bin/env python3
"""
roundup-forum-items-gate — §2.2: the roundup absorbs BuddyBoss's "New discussion: X".

⚠️ DELIBERATELY NOT REGISTERED IN run-all.sh YET. The behaviour it guards lives in
lg-follow-digest.php, which is a DEPLOYED mu-plugin — WordPress loads the serving
checkout's copy, so while §2.2 is unmerged this gate can say nothing about the branch and
would report CANNOT RUN for every lane. Registering it would turn "my feature is not
merged" into "nobody can get a green suite". It goes into run-all.sh in the same commit
that merges §2.2, exactly as follow-digest-gate.py was held out while its sender did not
exist (CRAFT-STANDARD row 13).

WHAT IT ASSERTS TODAY, all of it real:

  1. the tracked config carries 'forum_items', and its SHIPPED value is read not assumed
  2. the flag is consumed through lg_fd_forum_items(), never hardcoded
  3. BOTH halves exist — the discussion query AND the suppression seam
  4. ⚠️ and they are gated by the SAME switch. That coupling is the entire safety
     argument: suppressing BuddyBoss's "New discussion" while the roundup does not carry
     discussions takes a signal 38 members explicitly chose and gives nothing back — the
     mail black hole lg_fd_suppress_instant's own comment forbids. Two flags would make
     that state reachable; this asserts it is not.
  5. THE WORDING, executed rather than eyeballed: the pure subject/split functions are
     loaded in isolation (no WordPress needed) and run across every batch shape. The
     reply-only strings must match the pre-§2.2 text EXACTLY — that is what makes
     "flag OFF is a no-op" structural rather than a promise.

WHAT IT DOES NOT ASSERT, and will once §2.2 is deployed: items_for against a real
database, the suppression seam firing, and the renderer end-to-end. Those need the
branch's copy to be the one WordPress loads.

Exit codes follow run-all.sh: 0 green, 1 RED (real finding), 2 CANNOT RUN.
"""

import os
import re
import subprocess
import sys
import tempfile

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SENDER = os.path.join(REPO, "platform", "mu-plugins", "lg-follow-digest.php")
CONFIG = os.path.join(REPO, "platform", "config", "follow-digest.php")
SERVE = os.environ.get("LG_SERVE_ROOT", "/home/ubuntu/loothplatformv2-clean")

RED, GREEN, DEAD = [], [], []

# The exact strings this feature must not disturb. Written out here rather than derived
# from the code, because a table generated by the implementation agrees with the
# implementation no matter what it does.
HISTORIC = {
    (1, 1): "One new reply in a discussion you follow",
    (2, 1): "2 new replies in a discussion you follow",
    (2, 2): "2 new replies across 2 discussions you follow",
}

try:
    src = open(SENDER, encoding="utf-8").read()
except OSError:
    DEAD.append(f"cannot read {SENDER} — the sender this gate guards is not in the tree")
    src = ""

try:
    cfg = open(CONFIG, encoding="utf-8").read()
except OSError:
    DEAD.append(f"cannot read {CONFIG}")
    cfg = ""

# ── 1 + 2: the flag, read not assumed, and consumed through one reader ───────
if cfg:
    m = re.search(r"'forum_items'\s*=>\s*(true|false)", cfg)
    if m:
        GREEN.append(f"shipped default: follow-digest.php forum_items = {m.group(1)} (read, not assumed)")
    else:
        RED.append("platform/config/follow-digest.php no longer states 'forum_items' => true|false")

if src:
    if re.search(r"function lg_fd_forum_items\(\)", src):
        GREEN.append("the flag has a single reader, lg_fd_forum_items()")
    else:
        RED.append("lg_fd_forum_items() is gone — the flag has no reader, so nothing consumes it")

    # ── 3 + 4: both halves, and the SAME switch gating each ──────────────────
    disc_q = "s.type = 'forum'" in src
    seam = "add_filter( 'bb_send_forums_subscribed_discussion_email_notifications'" in src
    if disc_q:
        GREEN.append("the CONTENT half is present (a type='forum' subscription join)")
    else:
        RED.append("the discussion query is gone — the roundup would suppress BuddyBoss's "
                   "'New discussion' mail while carrying no discussions. That is the mail "
                   "black hole: 38 members lose a signal they explicitly chose.")
    if seam:
        GREEN.append("the SUPPRESSION half is present (bb_send_forums_subscribed_discussion_email_notifications)")
    else:
        RED.append("the discussion suppression seam is gone — members would get BuddyBoss's "
                   "'New discussion' AND the roundup's copy of it, which is the double-send "
                   "this project exists to end.")

    # the coupling: BOTH halves must test the same switch
    gated_content = bool(re.search(r"if \(\s*lg_fd_forum_items\(\)\s*\)", src))
    gated_seam = bool(re.search(r"if \(\s*!\s*lg_fd_forum_items\(\)\s*\)\s*\{\s*return \$send_mail", src))
    if gated_content and gated_seam:
        GREEN.append("⚠️ both halves are gated by the SAME switch — the replacement cannot lag the removal")
    else:
        RED.append(
            "the content and the suppression are no longer gated by the same switch "
            f"(content gated: {gated_content}, seam gated: {gated_seam}). Splitting them makes "
            "'suppressed but not replaced' reachable, which is the mail black hole."
        )

# ── 5: THE WORDING, executed in isolation ────────────────────────────────────
# Extracts the pure functions and runs them under plain php — no WordPress, no database,
# so this works whether or not the branch is the deployed copy.
if src and not DEAD:
    try:
        start = src.index("function lg_fd_split_kinds")
        end = src.index("function lg_fd_links_degraded")
        pure = src[start:end]
    except ValueError:
        pure = ""
        RED.append("could not locate the pure subject/split functions — the wording "
                   "assertions below cannot run, and they are what prove the OFF no-op")

    if pure:
        harness = """<?php
function wp_list_pluck($a,$k){ return array_map(fn($x)=>$x[$k] ?? null, $a); }
%s
$cases = [
  'r11' => [['topic_id'=>1]],
  'r21' => [['topic_id'=>1],['topic_id'=>1]],
  'r22' => [['topic_id'=>1],['topic_id'=>2]],
  'd1'  => [['topic_id'=>9,'kind'=>'discussion']],
  'd2'  => [['topic_id'=>9,'kind'=>'discussion'],['topic_id'=>8,'kind'=>'discussion']],
  'mix' => [['topic_id'=>1],['topic_id'=>9,'kind'=>'discussion']],
];
foreach ($cases as $k => $items) { echo $k, '=', lg_fd_subject(['items'=>$items]), "\\n"; }
""" % pure
        with tempfile.NamedTemporaryFile("w", suffix=".php", delete=False) as fh:
            fh.write(harness)
            hp = fh.name
        try:
            p = subprocess.run(["php", hp], capture_output=True, text=True, timeout=30)
            out = dict(l.split("=", 1) for l in p.stdout.splitlines() if "=" in l)
        except Exception as exc:  # noqa: BLE001
            out = {}
            DEAD.append(f"the wording harness could not run: {exc}")
        finally:
            os.unlink(hp)

        if out:
            for key, (n, t) in (("r11", (1, 1)), ("r21", (2, 1)), ("r22", (2, 2))):
                want = HISTORIC[(n, t)]
                got = out.get(key)
                if got == want:
                    GREEN.append(f"reply-only wording unchanged: {want!r}")
                else:
                    RED.append(
                        f"reply-only wording CHANGED: expected {want!r}, got {got!r}. With the "
                        "flag off this is what every existing roundup subject says, so a change "
                        "here is a change to mail that is already going out."
                    )
            # a discussion must never be described as a reply
            for key in ("d1", "d2"):
                got = out.get(key, "")
                if "discussion" in got and "repl" not in got:
                    GREEN.append(f"discussion-only wording is honest: {got!r}")
                else:
                    RED.append(f"a discussion-only batch is described as replies: {got!r}")
            mix = out.get("mix", "")
            if "repl" in mix and "discussion" in mix:
                GREEN.append(f"mixed wording names both kinds: {mix!r}")
            else:
                RED.append(f"a mixed batch does not name both kinds: {mix!r}")

# ── which copy would a runtime check exercise? ───────────────────────────────
served = os.path.join(SERVE, "platform", "mu-plugins", os.path.basename(SENDER))
try:
    import hashlib
    a = hashlib.md5(open(SENDER, "rb").read()).hexdigest()
    b = hashlib.md5(open(served, "rb").read()).hexdigest()
    if a == b:
        GREEN.append("branch and serving copies of the sender are identical — runtime legs "
                     "may be added to this gate now that they would test THIS code")
    else:
        GREEN.append(f"NOTE: branch ({a[:8]}) differs from serving ({b[:8]}), so §2.2 is "
                     "unmerged and the runtime legs are deliberately absent — see the header")
except OSError:
    GREEN.append("the sender is not deployed on this box — the branch copy is what runs")

for line in GREEN:
    print("  PASS  %s" % line)
for line in DEAD:
    print("  DEAD  %s" % line)
for line in RED:
    print("  FAIL  %s" % line)

if DEAD and not RED:
    print("roundup-forum-items: NO VERDICT (%d probe(s) could not run)" % len(DEAD))
    sys.exit(2)
if RED:
    print("roundup-forum-items: RED (%d finding(s))" % len(RED))
    sys.exit(1)
print("roundup-forum-items: GREEN (%d assertion(s))" % len(GREEN))
sys.exit(0)
