-- Expand skill_catalog: luthier craft + adjacent/tangential trades (machine shop, welding,
-- lumber processing, CNC/CAM/CAD, finishing, digital fab). ON CONFLICT (slug) DO NOTHING.

INSERT INTO skill_catalog (slug, name, category, sort_order) VALUES
  -- digital design / CAD-CAM-CNC
  ('cnc-programming','CNC programming (G-code)','design',300),
  ('cam-programming','CAM programming','design',302),
  ('cnc-operation','CNC operation','design',304),
  ('cnc-routing','CNC routing','design',306),
  ('2d-drafting','2D drafting','design',308),
  ('3d-modeling','3D modeling (CAD)','design',310),
  ('parametric-cad','Parametric CAD','design',312),
  ('vector-design','Vector design (Illustrator/Inkscape)','design',314),
  ('laser-cutting','Laser cutting / engraving','design',316),
  ('waterjet-cutting','Waterjet cutting','design',318),
  ('reverse-engineering','Reverse engineering / 3D scanning','design',320),
  ('resin-printing','Resin (SLA) 3D printing','design',322),
  -- machining
  ('manual-machining','Manual machining (lathe & mill)','machining',330),
  ('cnc-milling','CNC milling','machining',332),
  ('cnc-turning','CNC turning','machining',334),
  ('precision-grinding','Precision grinding','machining',336),
  ('metrology','Metrology / precision measurement','machining',338),
  -- metalwork
  ('tig-welding','TIG welding','metalwork',350),
  ('mig-welding','MIG welding','metalwork',352),
  ('stick-welding','Stick (arc) welding','metalwork',354),
  ('brazing','Brazing','metalwork',356),
  ('silver-soldering','Silver soldering','metalwork',358),
  ('sheet-metal','Sheet-metal fabrication','metalwork',360),
  ('blacksmithing','Blacksmithing / forging','metalwork',362),
  ('metal-casting','Metal casting','metalwork',364),
  ('hand-engraving','Hand engraving','metalwork',366),
  ('acid-etching','Acid etching','metalwork',368),
  ('anodizing','Anodizing / plating','metalwork',370),
  -- woodworking
  ('hand-tool-woodworking','Hand-tool woodworking','woodworking',380),
  ('fine-joinery','Fine joinery','woodworking',382),
  ('veneering','Veneering','woodworking',384),
  ('bent-lamination','Bent lamination','woodworking',386),
  ('steam-bending','Steam bending','woodworking',388),
  ('wood-carving','Wood carving','woodworking',390),
  ('marquetry','Marquetry','woodworking',392),
  ('wood-turning','Wood turning (lathe)','woodworking',394),
  ('router-work','Router work','woodworking',396),
  ('tool-sharpening','Tool sharpening','woodworking',398),
  ('hand-scraping','Hand scraping / planing','woodworking',400),
  -- materials / lumber processing
  ('lumber-milling','Lumber milling / sawing','materials',410),
  ('resawing','Resawing','materials',412),
  ('kiln-drying','Kiln drying','materials',414),
  ('tonewood-grading','Tonewood selection & grading','materials',416),
  ('moisture-control','Moisture / humidity control','materials',418),
  ('veneer-slicing','Veneer slicing','materials',420),
  ('blank-prep','Billet / blank prep','materials',422),
  ('sustainable-sourcing','Sustainable sourcing (CITES)','materials',424),
  -- finishing
  ('nitro-lacquer','Nitrocellulose lacquer','finish',430),
  ('water-based-finish','Water-based finishing','finish',432),
  ('oil-finish','Oil / hardwax finishing','finish',434),
  ('uv-finish','UV-cured finishing','finish',436),
  ('spray-finishing','Spray finishing','finish',438),
  ('french-polishing','French polishing','finish',440),
  ('buffing','Buffing & polishing','finish',442),
  ('color-matching','Finish color matching','finish',444),
  ('sunburst-spray','Sunburst spraying','finish',446),
  ('airbrushing','Airbrushing','finish',448),
  ('relic-aging','Relic / aged finishes','finish',450),
  -- electronics (extends existing)
  ('analog-circuit-design','Analog circuit design','electronics',460),
  ('pcb-design','PCB design','electronics',462),
  ('onboard-preamp','Onboard preamp systems','electronics',464),
  ('active-electronics','Active electronics','electronics',466),
  ('midi-systems','MIDI / digital pickups','electronics',468),
  -- build (extends existing)
  ('ukulele-build','Ukulele building','build',480),
  ('banjo-build','Banjo building','build',482),
  ('violin-build','Violin-family building','build',484),
  ('resonator-build','Resonator building','build',486),
  ('harp-build','Harp building','build',488),
  ('acoustic-bass-build','Acoustic bass building','build',490),
  -- adjacent crafts
  ('leatherwork','Leatherwork (straps / cases)','fabrication',500),
  ('case-making','Case & flightcase making','fabrication',502),
  ('plastics-fabrication','Plastics / acrylic fabrication','fabrication',504),
  ('pearl-cutting','Pearl / shell cutting','fabrication',506),
  ('pickguard-making','Pickguard fabrication','fabrication',508),
  ('hardware-fabrication','Custom hardware fabrication','fabrication',510)
ON CONFLICT (slug) DO NOTHING;
