#!/usr/bin/env bash
# publish-live-recap.sh — put the real-member recap deck behind the dev gate.
#
#   bash lg-weekly-digest/dev/publish-live-recap.sh
#   → https://dev2.loothgroup.com/v2/tests/output/wd-recap-live/index.html
#
# WHY THIS PATH AND NOT THE DOCROOT: dev2 is pull-only and nothing may be written
# into /var/www/dev (keeper, 2026-07-27). `location ^~ /v2/` aliases to
# /srv/lg-layout-v2/, which is a symlink into the SERVING CHECKOUT — but
# tests/output/ is gitignored there, so publishing adds nothing to the serve's
# porcelain and needs no serve window. Same path publish-previs.sh uses.
#
# NOTE the older render-recap-frames.php / render-recipient-frames.php wrote
# straight into /var/www/dev/mockups/wd-recap. That predates the pull-only rule and
# is not the pattern to copy — the SOURCE for everything published here is in the
# repo (dev/live-recap/, generated by dev/render-live-recap.php +
# dev/build-live-recap-deck.py). This script only copies.
set -euo pipefail

LANE="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SRC="$LANE/lg-weekly-digest/dev/live-recap"
DEST=/srv/lg-layout-v2/tests/output/wd-recap-live
URL=https://dev2.loothgroup.com/v2/tests/output/wd-recap-live/index.html

[ -f "$SRC/index.html" ] || { echo "no deck at $SRC — run render-live-recap.php then build-live-recap-deck.py"; exit 1; }

mkdir -p "$DEST"
cp "$SRC"/*.html "$DEST/"

# The publish target must not have dirtied the serving checkout. Prove it, do not
# assume it — porcelain is the only thing that can see a staged or untracked file.
SERVE=/home/ubuntu/loothplatformv2-clean
DIRT="$(git -C "$SERVE" status --porcelain | wc -l)"
echo "serve porcelain lines after publish: $DIRT  (must be 0)"
[ "$DIRT" -eq 0 ] || { echo "PUBLISH DIRTIED THE SERVE — stop and clean up"; exit 1; }

echo "published $(ls -1 "$DEST" | wc -l) files"
echo "$URL"
